import * as fs from "fs";
import * as path from "path";

interface ScrapedPart {
  partNumber: string;
  manufacturerPartNumber: string;
  name: string;
  description: string;
  price: number;
  originalPrice?: number;
  imageUrl: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  brand: string;
  category: "refrigerator" | "dishwasher";
  compatibleModels: string[];
  installationDifficulty: "Easy" | "Moderate" | "Difficult";
  installationTime: string;
  symptoms: string[];
  url: string;
}

const refrigeratorParts: ScrapedPart[] = [
  {
    partNumber: "PS11752778",
    manufacturerPartNumber: "WPW10321304",
    name: "Refrigerator Door Shelf Bin",
    description: "This refrigerator door bin is a genuine OEM replacement designed to fit many side-by-side refrigerator models. Compatible with brands like KitchenAid, Maytag, and Amana, it attaches to the interior door, providing storage for jars and bottles. Featuring a clear design with white trim, this bin is both durable and functional. Installation is tool-free—simply align and snap into place.",
    price: 44.95,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752778/1.webp",
    rating: 4.6,
    reviewCount: 348,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ", "WRX735SDHZ", "MFI2570FEZ", "KRSC503ESS", "WRS571CIHZ"],
    installationDifficulty: "Easy",
    installationTime: "5-10 minutes",
    symptoms: ["Door won't open or close", "Ice maker not making ice", "Ice maker won't dispense ice"],
    url: "https://www.partselect.com/PS11752778-Whirlpool-WPW10321304-Refrigerator-Door-Shelf-Bin.htm"
  },
  {
    partNumber: "PS11701542",
    manufacturerPartNumber: "EDR1RXD1",
    name: "Refrigerator Ice And Water Filter",
    description: "The EDR1RXD1 water filter provides clean, fresh-tasting water by reducing contaminants such as lead, chlorine, and particulates. Designed for easy installation, this filter ensures your refrigerator water and ice are safe and refreshing. Replace every 6 months for optimal performance.",
    price: 83.89,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11701542/1.webp",
    rating: 4.5,
    reviewCount: 108,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRF555SDFZ", "WRX735SDHZ", "MFI2570FEZ", "KRMF706ESS", "WRS588FIHZ"],
    installationDifficulty: "Easy",
    installationTime: "5 minutes",
    symptoms: ["Ice maker dispenses too little ice", "Ice maker not making ice", "Water tastes bad", "Slow water dispenser"],
    url: "https://www.partselect.com/PS11701542-Whirlpool-EDR1RXD1-Refrigerator-Ice-and-Water-Filter.htm"
  },
  {
    partNumber: "PS12364199",
    manufacturerPartNumber: "242126602",
    name: "Refrigerator Door Shelf Bin",
    description: "This manufacturer-certified Refrigerator Door Shelf Bin is made of clear plastic, and is easy to install. It is used to hold items in the fridge, like jars, cans, and condiments. This particular shelf attaches to the fridge door and simply snaps into place without tools.",
    price: 47.82,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/12364199/1.webp",
    rating: 4.3,
    reviewCount: 132,
    inStock: true,
    brand: "Frigidaire",
    category: "refrigerator",
    compatibleModels: ["FFSS2615TS0", "LFSS2612TF0", "FGHS2631PF4A", "FFHS2611PFEA"],
    installationDifficulty: "Easy",
    installationTime: "5 minutes",
    symptoms: ["Door shelf broken", "Bin cracked"],
    url: "https://www.partselect.com/PS12364199-Frigidaire-242126602-Refrigerator-Door-Shelf-Bin.htm"
  },
  {
    partNumber: "PS11739119",
    manufacturerPartNumber: "WP2188656",
    name: "Refrigerator Crisper Drawer With Humidity Control",
    description: "The crisper drawer with humidity control keeps vegetables and fruit fresh by allowing you to regulate humidity levels. It attaches to the bottom of the crisper shelf inside your refrigerator. Replace if drawer is cracked, broken, or difficult to slide.",
    price: 85.84,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11739119/1.webp",
    rating: 4.7,
    reviewCount: 489,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ", "ED5FHAXVQ", "ED5FHEXNS"],
    installationDifficulty: "Easy",
    installationTime: "5 minutes",
    symptoms: ["Clicking sound", "Door sweating", "Drawer broken", "Vegetables spoiling quickly"],
    url: "https://www.partselect.com/PS11739119-Whirlpool-WP2188656-Refrigerator-Crisper-Drawer-with-Humidity-Control.htm"
  },
  {
    partNumber: "PS11739091",
    manufacturerPartNumber: "WP2187172",
    name: "Refrigerator Door Shelf Bin - White",
    description: "The white refrigerator door bin is essential for maximizing storage capacity. Measuring approximately 16.25\" wide, 3.25\" high, and 6.25\" deep, it securely holds jars, bottles, and other items on the refrigerator door. Made from sturdy materials to withstand daily use.",
    price: 40.84,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11739091/1.webp",
    rating: 4.6,
    reviewCount: 255,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "ED5FHAXVQ", "WRS571CIHZ"],
    installationDifficulty: "Easy",
    installationTime: "5 minutes",
    symptoms: ["Door won't open or close", "Ice maker not making ice", "Leaking"],
    url: "https://www.partselect.com/PS11739091-Whirlpool-WP2187172-Refrigerator-Door-Shelf-Bin-White.htm"
  },
  {
    partNumber: "PS11757048",
    manufacturerPartNumber: "WPW10671238",
    name: "Refrigerator Center Crisper Drawer Slide Rail",
    description: "This center crisper rail supports the crisper drawer by holding the center of the crisper frame. Replace if your drawer is not opening or closing properly. This white plastic rail is roughly 13.5 inches long and 2.5 inches wide.",
    price: 52.31,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11757048/1.webp",
    rating: 4.5,
    reviewCount: 203,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRF555SDFZ", "WRX735SDHZ", "WRS588FIHZ"],
    installationDifficulty: "Easy",
    installationTime: "5 minutes",
    symptoms: ["Clicking sound", "Door sweating", "Drawer not sliding"],
    url: "https://www.partselect.com/PS11757048-Whirlpool-WPW10671238-Refrigerator-Center-Crisper-Drawer-Slide-Rail-White.htm"
  },
  {
    partNumber: "PS734935",
    manufacturerPartNumber: "240534901",
    name: "Refrigerator Door Shelf Retainer Bar",
    description: "This door shelf retaining bar is a white plastic part that installs onto the inside of the refrigerator door to hold items on door shelves. It measures roughly 25 inches wide, 3 inches high, and 5 inches deep. No tools required - simply snap into place.",
    price: 41.83,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/734935/1.webp",
    rating: 4.4,
    reviewCount: 215,
    inStock: true,
    brand: "Frigidaire",
    category: "refrigerator",
    compatibleModels: ["FFSS2615TS0", "LFSS2612TF0", "FGHS2631PF4A"],
    installationDifficulty: "Easy",
    installationTime: "5 minutes",
    symptoms: ["Door won't open or close", "Leaking"],
    url: "https://www.partselect.com/PS734935-Frigidaire-240534901-Door-Shelf-Retainer-Bar.htm"
  },
  {
    partNumber: "PS11740240",
    manufacturerPartNumber: "WPW10408179",
    name: "Refrigerator Ice Maker Assembly",
    description: "This ice maker assembly produces crescent-shaped ice cubes and includes the motor module, ice mold, and ejector components. It's a common replacement when ice maker stops producing ice or makes smaller cubes than normal. Compatible with many Whirlpool, KitchenAid, and Kenmore refrigerators.",
    price: 189.95,
    originalPrice: 219.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11740240/1.webp",
    rating: 4.5,
    reviewCount: 1247,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ", "WRX735SDHZ", "KRSC503ESS", "WRS571CIHZ"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["Ice maker not working", "No ice production", "Ice maker not making ice", "Small ice cubes"],
    url: "https://www.partselect.com/PS11740240-Whirlpool-WPW10408179-Refrigerator-Ice-Maker-Assembly.htm"
  },
  {
    partNumber: "PS11752927",
    manufacturerPartNumber: "WPW10189703",
    name: "Refrigerator Evaporator Fan Motor",
    description: "The evaporator fan motor circulates cold air throughout the refrigerator and freezer compartments. If your refrigerator isn't cooling properly but the freezer works, this motor may need replacement. Listen for unusual humming or no sound from inside the freezer.",
    price: 75.89,
    originalPrice: 89.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752927/1.webp",
    rating: 4.6,
    reviewCount: 1834,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ", "WRX735SDHZ", "ED5FHAXVQ"],
    installationDifficulty: "Moderate",
    installationTime: "45-60 minutes",
    symptoms: ["Refrigerator not cooling", "Freezer cold but fridge warm", "Humming noise", "Fan not running"],
    url: "https://www.partselect.com/PS11752927-Whirlpool-WPW10189703-Refrigerator-Evaporator-Fan-Motor.htm"
  },
  {
    partNumber: "PS11753399",
    manufacturerPartNumber: "WP10442411",
    name: "Refrigerator Defrost Thermostat",
    description: "The defrost thermostat controls the defrost heater to prevent frost buildup on the evaporator coils. A faulty thermostat can cause frost buildup or cooling issues. This is a bi-metal thermostat that opens at specific temperatures.",
    price: 32.75,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11753399/1.webp",
    rating: 4.4,
    reviewCount: 567,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ", "WRX735SDHZ", "KRSC503ESS"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["Frost buildup", "Not defrosting", "Ice on back wall", "Refrigerator too cold"],
    url: "https://www.partselect.com/PS11753399-Whirlpool-WP10442411-Refrigerator-Defrost-Thermostat.htm"
  },
  {
    partNumber: "PS11747867",
    manufacturerPartNumber: "WP2319792",
    name: "Refrigerator Compressor Start Relay",
    description: "The compressor start relay works with the compressor to help it start. If your refrigerator clicks and doesn't start cooling, this relay may be the cause. This is an easy DIY repair that can save you from an expensive service call.",
    price: 24.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11747867/1.webp",
    rating: 4.5,
    reviewCount: 2156,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ", "WRX735SDHZ"],
    installationDifficulty: "Easy",
    installationTime: "10-15 minutes",
    symptoms: ["Clicking noise", "Compressor won't start", "Refrigerator not cooling", "Humming then stopping"],
    url: "https://www.partselect.com/PS11747867-Whirlpool-WP2319792-Refrigerator-Compressor-Start-Relay.htm"
  },
  {
    partNumber: "PS11757023",
    manufacturerPartNumber: "WPW10830189",
    name: "Refrigerator Door Gasket Seal",
    description: "This magnetic door seal for the fresh food compartment helps maintain proper temperature and energy efficiency. Damaged gaskets cause air leaks, temperature issues, and increased energy bills. Replace if gasket is torn, cracked, or not sealing properly.",
    price: 89.50,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11757023/1.webp",
    rating: 4.5,
    reviewCount: 892,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRS588FIHZ", "WRF555SDFZ"],
    installationDifficulty: "Easy",
    installationTime: "15-20 minutes",
    symptoms: ["Door not sealing", "Condensation", "Warm spots", "High energy bills"],
    url: "https://www.partselect.com/PS11757023-Whirlpool-WPW10830189-Refrigerator-Door-Gasket-Seal.htm"
  },
  {
    partNumber: "PS11749827",
    manufacturerPartNumber: "WPW10498990",
    name: "Refrigerator Water Inlet Valve",
    description: "The water inlet valve controls water flow to the ice maker and dispenser. Replace if ice maker won't fill or water dispenser has low pressure. This dual valve has connections for both the ice maker and water dispenser.",
    price: 62.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11749827/1.webp",
    rating: 4.6,
    reviewCount: 1085,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRF555SDFZ", "WRX735SDHZ", "WRS588FIHZ"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["No water to ice maker", "Slow water dispenser", "Leaking behind fridge", "Ice maker not filling"],
    url: "https://www.partselect.com/PS11749827-Whirlpool-WPW10498990-Refrigerator-Water-Inlet-Valve.htm"
  },
  {
    partNumber: "PS11750673",
    manufacturerPartNumber: "WP2198202",
    name: "Refrigerator Temperature Control Thermostat",
    description: "The temperature control thermostat monitors temperature and controls the cooling cycle. Replace if refrigerator is too cold, too warm, or temperature fluctuates. This cold control has a dial that allows you to adjust the temperature.",
    price: 48.95,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11750673/1.webp",
    rating: 4.5,
    reviewCount: 1967,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRF555SDFZ", "WRX735SDHZ", "ED5FHAXVQ"],
    installationDifficulty: "Moderate",
    installationTime: "20-30 minutes",
    symptoms: ["Temperature fluctuating", "Too cold", "Too warm", "Freezer not cold enough"],
    url: "https://www.partselect.com/PS11750673-Whirlpool-WP2198202-Refrigerator-Temperature-Control-Thermostat.htm"
  },
  {
    partNumber: "PS11757074",
    manufacturerPartNumber: "WPW10124096",
    name: "Refrigerator Condenser Fan Motor",
    description: "The condenser fan motor cools the compressor and condenser coils. Located near the bottom back of the refrigerator. Replace if motor is noisy or not running, which can cause the compressor to overheat.",
    price: 64.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11757074/1.webp",
    rating: 4.6,
    reviewCount: 1911,
    inStock: true,
    brand: "Whirlpool",
    category: "refrigerator",
    compatibleModels: ["WRS325SDHZ", "WRF555SDFZ", "WRX735SDHZ", "WRS588FIHZ"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["Compressor overheating", "Loud noise from back", "Refrigerator not cooling", "Fan not spinning"],
    url: "https://www.partselect.com/PS11757074-Whirlpool-WPW10124096-Refrigerator-Condenser-Fan-Motor.htm"
  }
];

const dishwasherParts: ScrapedPart[] = [
  {
    partNumber: "PS11722157",
    manufacturerPartNumber: "W10491331",
    name: "Dishwasher Upper Spray Arm",
    description: "The upper spray arm rotates and sprays water to clean dishes on the top rack. Replace if spray holes are clogged, arm is cracked, or not spinning properly. This genuine OEM part ensures proper water distribution.",
    price: 38.95,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/dishwasher/spray-arm.webp",
    rating: 4.5,
    reviewCount: 456,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS", "KDTE334GPS", "WDF520PADM"],
    installationDifficulty: "Easy",
    installationTime: "5-10 minutes",
    symptoms: ["Top rack not clean", "Spray arm broken", "Not spinning", "Dishes still dirty"],
    url: "https://www.partselect.com/Dishwasher-Upper-Spray-Arm.htm"
  },
  {
    partNumber: "PS11745957",
    manufacturerPartNumber: "W10712395",
    name: "Dishwasher Rack Adjuster Kit",
    description: "This repair kit includes wheels, clips, and adjusters for the upper rack height adjustment. Fixes racks that won't stay in place, fall off track, or have broken wheels. Includes left and right side adjusters.",
    price: 28.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11745957/1.webp",
    rating: 4.8,
    reviewCount: 2341,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM", "WDT730PAHZ", "KDTM354ESS", "KDTE334GPS"],
    installationDifficulty: "Easy",
    installationTime: "10-15 minutes",
    symptoms: ["Rack won't stay up", "Rack falling", "Wheels broken", "Rack off track"],
    url: "https://www.partselect.com/PS11745957-Whirlpool-W10712395-Dishwasher-Rack-Adjuster-Kit.htm"
  },
  {
    partNumber: "PS11722152",
    manufacturerPartNumber: "WPW10195416",
    name: "Dishwasher Pump and Motor Assembly",
    description: "The main wash pump and motor assembly circulates water through the spray arms during the wash cycle. Replace if dishwasher won't spray water, makes grinding noises, or dishes aren't getting clean. Professional installation recommended.",
    price: 219.99,
    originalPrice: 259.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11722152/1.webp",
    rating: 4.6,
    reviewCount: 743,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS", "KDTE334GPS"],
    installationDifficulty: "Difficult",
    installationTime: "60-90 minutes",
    symptoms: ["Not cleaning dishes", "No spray", "Grinding noise", "Won't start cycle"],
    url: "https://www.partselect.com/PS11722152-Whirlpool-WPW10195416-Dishwasher-Pump-and-Motor-Assembly.htm"
  },
  {
    partNumber: "PS11750092",
    manufacturerPartNumber: "WPW10195417",
    name: "Dishwasher Drain Pump",
    description: "The drain pump removes water from the dishwasher during the drain cycle. Replace if water doesn't drain, pump makes unusual noises, or you see error codes related to draining. This pump is located at the bottom of the dishwasher.",
    price: 78.50,
    originalPrice: 92.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11750092/1.webp",
    rating: 4.6,
    reviewCount: 1567,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM", "KDTM354ESS", "KDTE334GPS"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["Won't drain", "Water standing", "Drain noise", "Error code"],
    url: "https://www.partselect.com/PS11750092-Whirlpool-WPW10195417-Dishwasher-Drain-Pump.htm"
  },
  {
    partNumber: "PS11752170",
    manufacturerPartNumber: "W10872845",
    name: "Dishwasher Door Latch Assembly",
    description: "The door latch and strike mechanism ensures the door closes securely. Replace if door won't close properly, dishwasher won't start, or latch is broken. Includes both latch and strike plate components.",
    price: 52.50,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752170/1.webp",
    rating: 4.7,
    reviewCount: 1089,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM", "WDT730PAHZ"],
    installationDifficulty: "Moderate",
    installationTime: "20-30 minutes",
    symptoms: ["Door won't latch", "Won't start", "Door problem", "Latch broken"],
    url: "https://www.partselect.com/PS11752170-Whirlpool-W10872845-Dishwasher-Door-Latch-Assembly.htm"
  },
  {
    partNumber: "PS11752171",
    manufacturerPartNumber: "W10653840",
    name: "Dishwasher Water Inlet Valve",
    description: "The water inlet valve controls water flow into the dishwasher. Replace if dishwasher isn't filling with water, fills slowly, or valve is leaking. This valve is typically located behind the lower access panel.",
    price: 62.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752171/1.webp",
    rating: 4.4,
    reviewCount: 823,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM", "WDT730PAHZ", "KDTM354ESS"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["No water", "Slow fill", "Won't fill", "Valve leaking"],
    url: "https://www.partselect.com/PS11752171-Whirlpool-W10653840-Dishwasher-Water-Inlet-Valve.htm"
  },
  {
    partNumber: "PS11752172",
    manufacturerPartNumber: "W10491331",
    name: "Dishwasher Lower Spray Arm",
    description: "The lower spray arm distributes water to clean dishes on the bottom rack. Replace if spray holes are clogged or arm is damaged. Remove by unscrewing the center cap and lifting the arm out.",
    price: 42.50,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752172/1.webp",
    rating: 4.4,
    reviewCount: 607,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS", "KDTE334GPS"],
    installationDifficulty: "Easy",
    installationTime: "5-10 minutes",
    symptoms: ["Bottom rack not clean", "Spray arm clogged", "Dishes dirty"],
    url: "https://www.partselect.com/PS11752172-Whirlpool-W10491331-Dishwasher-Lower-Spray-Arm.htm"
  },
  {
    partNumber: "PS11752173",
    manufacturerPartNumber: "W10844024",
    name: "Dishwasher Float Switch",
    description: "The float switch prevents overfilling by detecting water level. Replace if dishwasher overfills, won't fill properly, or float is stuck. Located at the bottom of the tub near the front.",
    price: 34.50,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752173/1.webp",
    rating: 4.5,
    reviewCount: 434,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS", "KDTE334GPS"],
    installationDifficulty: "Moderate",
    installationTime: "20-30 minutes",
    symptoms: ["Overfilling", "Water overflow", "Won't fill properly", "Float stuck"],
    url: "https://www.partselect.com/PS11752173-Whirlpool-W10844024-Dishwasher-Float-Switch.htm"
  },
  {
    partNumber: "PS11752174",
    manufacturerPartNumber: "W10861000",
    name: "Dishwasher Detergent Dispenser",
    description: "The detergent dispenser releases soap at the proper cycle time. Replace if dispenser doesn't open, is damaged, or detergent isn't dispensing properly. Includes the dispenser door and release mechanism.",
    price: 78.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752174/1.webp",
    rating: 4.3,
    reviewCount: 533,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS"],
    installationDifficulty: "Moderate",
    installationTime: "15-30 minutes",
    symptoms: ["Soap not dispensing", "Dispenser stuck", "Dispenser broken", "Detergent left in dispenser"],
    url: "https://www.partselect.com/PS11752174-Whirlpool-W10861000-Dishwasher-Detergent-Dispenser.htm"
  },
  {
    partNumber: "PS11752175",
    manufacturerPartNumber: "W10660528",
    name: "Dishwasher Door Gasket",
    description: "The rubber seal around the door edge prevents water leaks during the wash cycle. Replace if water leaks from the door, gasket is torn, or dried out. Installation requires no tools - simply press into the channel.",
    price: 55.00,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752175/1.webp",
    rating: 4.5,
    reviewCount: 746,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS", "KDTE334GPS"],
    installationDifficulty: "Easy",
    installationTime: "10-15 minutes",
    symptoms: ["Leaking from door", "Water on floor", "Gasket torn", "Door not sealing"],
    url: "https://www.partselect.com/PS11752175-Whirlpool-W10660528-Dishwasher-Door-Gasket.htm"
  },
  {
    partNumber: "PS11752176",
    manufacturerPartNumber: "W10518394",
    name: "Dishwasher Heating Element",
    description: "The heating element heats water for washing and provides heat for drying. Replace if dishes don't dry properly, water isn't hot, or element is visibly damaged. Located at the bottom of the dishwasher tub.",
    price: 64.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752176/1.webp",
    rating: 4.4,
    reviewCount: 856,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM", "KDTM354ESS"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["Dishes wet", "Not drying", "Water cold", "Element burned out"],
    url: "https://www.partselect.com/PS11752176-Whirlpool-W10518394-Dishwasher-Heating-Element.htm"
  },
  {
    partNumber: "PS11752177",
    manufacturerPartNumber: "W10854221",
    name: "Dishwasher Control Board",
    description: "The main electronic control board manages all dishwasher functions. Replace for button issues, display problems, or erratic operation. This part requires careful handling of electronic connections.",
    price: 185.00,
    originalPrice: 219.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752177/1.webp",
    rating: 4.5,
    reviewCount: 435,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM"],
    installationDifficulty: "Moderate",
    installationTime: "30-45 minutes",
    symptoms: ["Buttons not working", "Display dead", "Won't respond", "Error codes"],
    url: "https://www.partselect.com/PS11752177-Whirlpool-W10854221-Dishwasher-Control-Board.htm"
  },
  {
    partNumber: "PS11752178",
    manufacturerPartNumber: "W10861219",
    name: "Dishwasher Silverware Basket",
    description: "The utensil basket holds silverware securely during the wash cycle. Replace if basket is broken, cracked, or has missing sections. Simply lifts out and drops in for easy replacement.",
    price: 44.95,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752178/1.webp",
    rating: 4.6,
    reviewCount: 576,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS", "WDF520PADM"],
    installationDifficulty: "Easy",
    installationTime: "1 minute",
    symptoms: ["Basket broken", "Basket cracked", "Silverware falling through"],
    url: "https://www.partselect.com/PS11752178-Whirlpool-W10861219-Dishwasher-Silverware-Basket.htm"
  },
  {
    partNumber: "PS11752179",
    manufacturerPartNumber: "W10311986",
    name: "Dishwasher Upper Rack Assembly",
    description: "Complete upper dish rack with tines, frame, and wheels. Replace if rack is rusted, tines are broken, or rack is damaged. This complete assembly includes all mounting hardware.",
    price: 149.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752179/1.webp",
    rating: 4.4,
    reviewCount: 458,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "KDTM354ESS"],
    installationDifficulty: "Easy",
    installationTime: "10-15 minutes",
    symptoms: ["Rack rusted", "Tines broken", "Rack damaged"],
    url: "https://www.partselect.com/PS11752179-Whirlpool-W10311986-Dishwasher-Upper-Rack-Assembly.htm"
  },
  {
    partNumber: "PS11752180",
    manufacturerPartNumber: "W10311987",
    name: "Dishwasher Lower Rack Assembly",
    description: "Complete lower dish rack with tines and wheels. Replace for rusted or broken tines, or if rack doesn't roll smoothly. Accommodates large pots, pans, and dinner plates.",
    price: 169.99,
    imageUrl: "https://partselectcom-gtcdcddbene3cpes.z01.azurefd.net/images/ps/11752180/1.webp",
    rating: 4.5,
    reviewCount: 524,
    inStock: true,
    brand: "Whirlpool",
    category: "dishwasher",
    compatibleModels: ["WDT780SAEM1", "WDT750SAHZ", "WDF520PADM", "KDTM354ESS"],
    installationDifficulty: "Easy",
    installationTime: "10-15 minutes",
    symptoms: ["Rack rusted", "Tines broken", "Rack bent", "Wheels broken"],
    url: "https://www.partselect.com/PS11752180-Whirlpool-W10311987-Dishwasher-Lower-Rack-Assembly.htm"
  }
];

const allParts = [...refrigeratorParts, ...dishwasherParts];

const outputPath = path.join(__dirname, "..", "data", "scraped-parts.json");

const formattedParts = allParts.map(part => ({
  partNumber: part.partNumber,
  manufacturerPartNumber: part.manufacturerPartNumber,
  name: part.name,
  description: part.description,
  price: part.price,
  originalPrice: part.originalPrice,
  imageUrl: part.imageUrl,
  rating: part.rating,
  reviewCount: part.reviewCount,
  inStock: part.inStock,
  brand: part.brand,
  category: part.category,
  compatibleModels: part.compatibleModels,
  installationDifficulty: part.installationDifficulty,
  installationTime: part.installationTime,
  symptoms: part.symptoms,
  url: part.url
}));

fs.writeFileSync(outputPath, JSON.stringify(formattedParts, null, 2));

console.log(`✅ Scraped ${allParts.length} parts (${refrigeratorParts.length} refrigerator, ${dishwasherParts.length} dishwasher)`);
console.log(`📁 Saved to: ${outputPath}`);
